-- =============================================================================
-- Service Track Pro – Scheduler Tables
-- Run this in your Supabase SQL editor (https://app.supabase.com → SQL Editor).
-- This script is idempotent: safe to run on a fresh project or re-run.
--
-- Depends on: schema_setup.sql (companies table + get_my_company_id() function
-- must already exist before running this file).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. SCHEDULE CREWS
--    One row per crew per company. The `id` is a UUID string generated by
--    the React front-end (crypto.randomUUID()).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schedule_crews (
  id          TEXT PRIMARY KEY,            -- UUID string from crypto.randomUUID()
  company_id  UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name        TEXT NOT NULL DEFAULT '',
  member_ids  BIGINT[] NOT NULL DEFAULT '{}',  -- employee.id values
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE schedule_crews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "schedule_crews_select" ON schedule_crews;
CREATE POLICY "schedule_crews_select" ON schedule_crews
  FOR SELECT USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_crews_insert" ON schedule_crews;
CREATE POLICY "schedule_crews_insert" ON schedule_crews
  FOR INSERT WITH CHECK (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_crews_update" ON schedule_crews;
CREATE POLICY "schedule_crews_update" ON schedule_crews
  FOR UPDATE USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_crews_delete" ON schedule_crews;
CREATE POLICY "schedule_crews_delete" ON schedule_crews
  FOR DELETE USING (company_id = get_my_company_id());

CREATE INDEX IF NOT EXISTS schedule_crews_company_idx ON schedule_crews (company_id);

-- ---------------------------------------------------------------------------
-- 2. SCHEDULE JOB OPTIONS
--    The scheduler's own list of jobs available to schedule (separate from
--    the main `jobs` table which tracks customer work-logs and invoices).
--    job_number must be unique within a company.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schedule_job_options (
  id             BIGSERIAL PRIMARY KEY,
  company_id     UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  job_number     TEXT NOT NULL,
  location       TEXT NOT NULL DEFAULT '',
  estimated_days INT  NOT NULL DEFAULT 1 CHECK (estimated_days >= 1),
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (company_id, job_number)
);

ALTER TABLE schedule_job_options ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "schedule_job_options_select" ON schedule_job_options;
CREATE POLICY "schedule_job_options_select" ON schedule_job_options
  FOR SELECT USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_job_options_insert" ON schedule_job_options;
CREATE POLICY "schedule_job_options_insert" ON schedule_job_options
  FOR INSERT WITH CHECK (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_job_options_update" ON schedule_job_options;
CREATE POLICY "schedule_job_options_update" ON schedule_job_options
  FOR UPDATE USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_job_options_delete" ON schedule_job_options;
CREATE POLICY "schedule_job_options_delete" ON schedule_job_options
  FOR DELETE USING (company_id = get_my_company_id());

CREATE INDEX IF NOT EXISTS schedule_job_options_company_idx ON schedule_job_options (company_id);

-- ---------------------------------------------------------------------------
-- 3. SCHEDULE BLOCKS
--    One row per block placed on the Gantt timeline. The `id` is a UUID
--    string generated by the React front-end (crypto.randomUUID()).
--    `crew_id` references schedule_crews.id; `job_number` is a soft
--    reference to schedule_job_options.job_number (no FK so delay-type
--    blocks with synthetic labels still persist cleanly).
--    `equipment_ids` stores the BIGINT ids of equipment table rows that
--    are assigned to be on site for this block.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schedule_blocks (
  id             TEXT PRIMARY KEY,          -- UUID string from crypto.randomUUID()
  company_id     UUID    NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  crew_id        TEXT    NOT NULL REFERENCES schedule_crews(id) ON DELETE CASCADE,
  job_number     TEXT    NOT NULL,
  start_date     DATE    NOT NULL,
  duration_days  INT     NOT NULL DEFAULT 1 CHECK (duration_days >= 1),
  type           TEXT    NOT NULL DEFAULT 'job' CHECK (type IN ('job', 'delay')),
  extended       BOOLEAN NOT NULL DEFAULT FALSE,
  equipment_ids  BIGINT[] NOT NULL DEFAULT '{}',   -- equipment.id values
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE schedule_blocks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "schedule_blocks_select" ON schedule_blocks;
CREATE POLICY "schedule_blocks_select" ON schedule_blocks
  FOR SELECT USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_blocks_insert" ON schedule_blocks;
CREATE POLICY "schedule_blocks_insert" ON schedule_blocks
  FOR INSERT WITH CHECK (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_blocks_update" ON schedule_blocks;
CREATE POLICY "schedule_blocks_update" ON schedule_blocks
  FOR UPDATE USING (company_id = get_my_company_id());

DROP POLICY IF EXISTS "schedule_blocks_delete" ON schedule_blocks;
CREATE POLICY "schedule_blocks_delete" ON schedule_blocks
  FOR DELETE USING (company_id = get_my_company_id());

CREATE INDEX IF NOT EXISTS schedule_blocks_company_idx  ON schedule_blocks (company_id);
CREATE INDEX IF NOT EXISTS schedule_blocks_crew_idx     ON schedule_blocks (crew_id);
CREATE INDEX IF NOT EXISTS schedule_blocks_date_idx     ON schedule_blocks (start_date);
